import { Inter } from "next/font/google";
import "./globals.css";
import Signup from "./auth/signup";
import * as React from "react";

// 1. import `NextUIProvider` component
import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
  
    <NextUIProvider>
      <YourApplication />
    </NextUIProvider>
 
      <Signup />

    </html>
  );
}



